# Generated by Django 2.1.8 on 2019-08-28 12:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Group_buy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stime', models.DateTimeField(default='2019-7-20 15:30:30')),
                ('ltime', models.DateTimeField(default='2019-7-30 15:30:30')),
            ],
            options={
                'verbose_name': '商品团购表',
                'verbose_name_plural': '商品团购表',
                'db_table': 'group_buy',
            },
        ),
        migrations.CreateModel(
            name='Pro_discass',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dis_content', models.CharField(max_length=200, verbose_name='评论内容')),
            ],
            options={
                'verbose_name': '评论表',
                'verbose_name_plural': '评论表',
            },
        ),
        migrations.CreateModel(
            name='Pro_sku',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default='images/product_AD_07.png', null=True, upload_to='static/images', verbose_name='商品图片')),
                ('name', models.CharField(max_length=50, verbose_name='商品名(规格)')),
                ('describe', models.CharField(max_length=600, null=True, verbose_name='产品介绍')),
                ('size', models.CharField(default='500g', max_length=10, verbose_name='产品规格')),
                ('title', models.CharField(max_length=100, verbose_name='标签')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='本店价')),
                ('cost_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='市场价')),
                ('stock', models.IntegerField(default=0, verbose_name='库存')),
                ('sales', models.IntegerField(default=0, verbose_name='销量')),
                ('comments', models.IntegerField(default=0, verbose_name='评价数')),
                ('is_putaway', models.BooleanField(default=True, verbose_name='是否上架销售')),
            ],
            options={
                'verbose_name': '商品SKU',
                'verbose_name_plural': '商品SKU',
                'db_table': 'Pro_sku',
            },
        ),
        migrations.CreateModel(
            name='Pro_Type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30, verbose_name='分类名称')),
                ('desc', models.CharField(default='商品描述', max_length=200, verbose_name='描述')),
                ('is_delete', models.BooleanField(default=False, verbose_name='删除')),
            ],
            options={
                'verbose_name': '商品分类',
                'verbose_name_plural': '商品分类',
            },
        ),
        migrations.CreateModel(
            name='Reply_dis',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reply_content', models.CharField(max_length=200, verbose_name='回复内容')),
                ('reply_dis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='integral_app.Pro_discass')),
                ('reply_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_app.UserInfo')),
            ],
            options={
                'verbose_name': '回复表',
                'verbose_name_plural': '回复表',
            },
        ),
        migrations.AddField(
            model_name='pro_sku',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='integral_app.Pro_Type'),
        ),
        migrations.AddField(
            model_name='pro_discass',
            name='dis_pro',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='integral_app.Pro_sku'),
        ),
        migrations.AddField(
            model_name='pro_discass',
            name='dis_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_app.UserInfo'),
        ),
        migrations.AddField(
            model_name='group_buy',
            name='group_pro',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='integral_app.Pro_sku'),
        ),
    ]
