# Generated by Django 2.1.8 on 2019-07-21 13:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0001_initial'),
        ('integral_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pro_discass',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dis_content', models.CharField(max_length=200, verbose_name='评论内容')),
                ('dis_pro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='integral_app.Pro_sku')),
                ('dis_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_app.UserInfo')),
            ],
        ),
        migrations.CreateModel(
            name='Reply_dis',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reply_content', models.CharField(max_length=200, verbose_name='回复内容')),
                ('reply_dis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='integral_app.Pro_discass')),
                ('reply_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_app.UserInfo')),
            ],
        ),
    ]
