# Generated by Django 2.1.8 on 2019-09-14 03:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('integral_app', '0002_auto_20190912_1705'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pro_discass',
            name='dis_pro',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='integral_app.Pro_sku', verbose_name='评论商品'),
        ),
        migrations.AlterField(
            model_name='pro_discass',
            name='dis_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_app.UserInfo', verbose_name='评论用户'),
        ),
        migrations.AlterField(
            model_name='reply_dis',
            name='reply_dis',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='integral_app.Pro_discass', verbose_name='回复评论'),
        ),
        migrations.AlterField(
            model_name='reply_dis',
            name='reply_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_app.UserInfo', verbose_name='回复用户'),
        ),
    ]
