# Generated by Django 2.1.8 on 2019-07-25 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integral_app', '0002_pro_discass_reply_dis'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pro_sku',
            name='image',
            field=models.ImageField(default='images/product_AD_07.png', null=True, upload_to='static/images', verbose_name='商品图片'),
        ),
    ]
