# Generated by Django 2.1.8 on 2019-08-31 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integral_app', '0002_collect'),
    ]

    operations = [
        migrations.AddField(
            model_name='pro_sku',
            name='is_index',
            field=models.BooleanField(default=False, verbose_name='是否促销首页'),
        ),
    ]
