# Generated by Django 2.1.8 on 2019-09-10 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_order',
            name='transit_price',
            field=models.DecimalField(decimal_places=2, default=10.0, max_digits=8, verbose_name='运费'),
        ),
    ]
