# Generated by Django 2.1.8 on 2019-08-29 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='is_active',
            field=models.IntegerField(default=0, verbose_name='是否激活'),
        ),
    ]
