# Generated by Django 2.1.8 on 2019-08-28 01:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='adress',
            name='city_name',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='user_app.City'),
        ),
        migrations.AddField(
            model_name='adress',
            name='county_name',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='user_app.County'),
        ),
        migrations.AddField(
            model_name='adress',
            name='province_name',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='user_app.Province'),
        ),
    ]
