# Generated by Django 2.1.8 on 2019-07-25 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='birthday',
            field=models.DateField(auto_now=True, null=True, verbose_name='生日'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='head_img',
            field=models.ImageField(default='images/product_img_17.png', upload_to='static/images', verbose_name='头像'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='up_time',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='注册时间'),
        ),
    ]
