# Generated by Django 2.1.8 on 2019-07-25 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0002_auto_20190725_0855'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='birthday',
            field=models.DateField(null=True, verbose_name='生日'),
        ),
    ]
