# Generated by Django 2.1.8 on 2019-07-29 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0003_auto_20190725_0916'),
    ]

    operations = [
        migrations.AddField(
            model_name='adress',
            name='area',
            field=models.CharField(max_length=50, null=True, verbose_name='地区'),
        ),
        migrations.AddField(
            model_name='adress',
            name='postcode',
            field=models.CharField(max_length=20, null=True, verbose_name='邮编'),
        ),
    ]
