# Generated by Django 2.1.8 on 2019-09-17 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0003_auto_20190914_1129'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='birthday',
            field=models.DateField(blank=True, null=True, verbose_name='生日'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='head_img',
            field=models.ImageField(default='images/product_img_17.png', upload_to='static/images', verbose_name='头像'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='t_name',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='真实姓名'),
        ),
    ]
