# Generated by Django 2.1.8 on 2019-07-31 14:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0004_auto_20190729_0840'),
    ]

    operations = [
        migrations.CreateModel(
            name='Collect',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(null=True, upload_to='', verbose_name='商品图片')),
                ('name', models.CharField(max_length=50, verbose_name='商品名(规格)')),
                ('size', models.CharField(default='500g', max_length=10, verbose_name='产品规格')),
                ('title', models.CharField(max_length=100, verbose_name='标签')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_app.UserInfo')),
            ],
        ),
    ]
