# Generated by Django 2.1.8 on 2019-07-31 15:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0006_collect_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collect',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='user_app.UserInfo'),
        ),
    ]
