# Generated by Django 2.1.8 on 2019-07-31 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0007_auto_20190731_2319'),
    ]

    operations = [
        migrations.AddField(
            model_name='collect',
            name='pro_id',
            field=models.IntegerField(null=True, unique=True, verbose_name='商品id'),
        ),
    ]
