# Generated by Django 2.1.8 on 2019-08-28 01:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('integral_app', '0001_initial'),
        ('user_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CartInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ccount', models.IntegerField()),
                ('cprice', models.DecimalField(decimal_places=2, max_digits=10)),
                ('pros', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='integral_app.Pro_sku')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='user_app.UserInfo')),
            ],
            options={
                'verbose_name': '购物车',
                'verbose_name_plural': '购物车',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('oprice', models.DecimalField(decimal_places=2, max_digits=5)),
                ('ocount', models.IntegerField()),
                ('oprices', models.DecimalField(decimal_places=2, max_digits=8)),
                ('oadress', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='user_app.Adress')),
                ('pro_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='integral_app.Pro_sku')),
            ],
            options={
                'verbose_name': '确认订单管理',
                'verbose_name_plural': '确认订单管理',
            },
        ),
    ]
