# Generated by Django 2.1.8 on 2019-09-10 01:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user_app', '0001_initial'),
        ('integral_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CartInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ccount', models.IntegerField(default=1, verbose_name='商品数量')),
                ('cprice', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='商品总价')),
                ('pros', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='integral_app.Pro_sku', verbose_name='商品')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_app.UserInfo', verbose_name='用户')),
            ],
            options={
                'verbose_name': '购物车',
                'verbose_name_plural': '购物车',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField(default=1, verbose_name='商品数量')),
                ('prices', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='小计')),
                ('comment', models.CharField(default='', max_length=200, verbose_name='留言评论')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_app.User_order', verbose_name='订单信息表')),
                ('pro_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='integral_app.Pro_sku', verbose_name='商品sku')),
            ],
            options={
                'verbose_name': '订单商品表',
                'verbose_name_plural': '订单商品表',
            },
        ),
    ]
