# Generated by Django 2.1.8 on 2019-07-21 12:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user_app', '0001_initial'),
        ('integral_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CartInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ccount', models.IntegerField(db_column='cart_count', verbose_name='数量')),
                ('pros', models.ForeignKey(db_column='good_id', on_delete=django.db.models.deletion.CASCADE, to='integral_app.Pro_sku')),
                ('user', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, to='user_app.UserInfo')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('oprice', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='单价')),
                ('ocount', models.IntegerField(verbose_name='数量')),
                ('oprices', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='总价')),
                ('orderNo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_app.User_order')),
                ('pro_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='integral_app.Pro_sku')),
            ],
        ),
    ]
