# Generated by Django 2.1.8 on 2019-09-03 08:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartinfo',
            name='ccount',
        ),
        migrations.RemoveField(
            model_name='cartinfo',
            name='cprice',
        ),
    ]
