# Generated by Django 2.1.1 on 2019-08-02 00:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop_app', '0002_remove_order_orderno'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartinfo',
            name='cprice',
            field=models.DecimalField(decimal_places=2, default=40.0, max_digits=10, verbose_name='小计'),
        ),
        migrations.AlterField(
            model_name='cartinfo',
            name='ccount',
            field=models.IntegerField(default=1, verbose_name='数量'),
        ),
        migrations.AlterField(
            model_name='cartinfo',
            name='pros',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='integral_app.Pro_sku'),
        ),
        migrations.AlterField(
            model_name='cartinfo',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_app.UserInfo'),
        ),
    ]
