# Generated by Django 2.1.8 on 2019-08-01 13:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop_app', '0002_remove_order_orderno'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartinfo',
            name='pros',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='integral_app.Pro_sku'),
        ),
        migrations.AlterField(
            model_name='cartinfo',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_app.UserInfo'),
        ),
    ]
