# Generated by Django 2.1.1 on 2019-08-02 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_app', '0003_auto_20190802_0851'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartinfo',
            name='cprice',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='小计'),
        ),
    ]
