# Generated by Django 2.1.8 on 2019-08-02 03:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop_app', '0004_auto_20190802_0903'),
        ('shop_app', '0003_auto_20190801_2112'),
    ]

    operations = [
    ]
